//
// Created by Alejandro on 28/08/16.
//

#ifndef TEST_CLIENT_TEXTURES_H
#define TEST_CLIENT_TEXTURES_H

enum Textures
{
    CROSSHAIR,
    PLAYER_RED,
    PLAYER_GREEN,
    BULLET_SMALL,
    FLOOR_PURPLE_CHESS,
    FLOOR_BLUE_BRICK,
    SKULL,
    RED_DEAD,
    GREEN_DEAD,
	HUD_AMMO
};

#endif //TEST_CLIENT_TEXTURES_H
